Add board color props and update board information
acm-ucr/ieee-website pull request #69
Opened 2023-04-22 20:22 UTC by nguyena537

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/63137037/233805155-1edf7fda-fedb-436e-80c2-4e9eb226a1d3.png">

2023-04-22 21:15 UTC, menthy-wu requested changes
can you remove the picture, like it shows in the issue description

2023-04-24 03:54 UTC, nguyena537 commented
<img width="561" alt="image" src="https://user-images.githubusercontent.com/63137037/233896434-1e8105c8-bd9d-403c-9214-72ee600b23d2.png">
Will work on extending the vertical bar

2023-05-01 23:07 UTC, nguyena537 commented
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/63137037/235546671-31cc31de-9086-488f-b7f6-e98a6829c4dd.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/63137037/235546684-d8224d70-c101-45c5-bd0d-42a040024433.png">

2023-05-02 02:45 UTC, menthy-wu approved these changes

2023-05-02 02:45 UTC, merged